# Generated by Django 3.0.2 on 2020-01-20 14:15

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ISO numeric')),
                ('code', models.CharField(max_length=4, verbose_name='Code (ISO)')),
                ('name', models.CharField(max_length=128, verbose_name='Official name (CAPS)')),
                ('symbol', models.CharField(blank=True, max_length=3, null=True, verbose_name='Symbol')),
                ('is_active', models.BooleanField(default=True)),
                ('rate', models.FloatField(default=1.0)),
                ('precision', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_data', common.fields.JsonField(null=True)),
                ('products_data', common.fields.JsonField(default=[])),
                ('details', models.TextField(blank=True, null=True)),
                ('products_price', models.BigIntegerField(null=True)),
                ('total_price', models.BigIntegerField(null=True)),
                ('delivery_data', common.fields.JsonField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(default=840, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Currency')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='common.Customer')),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.DeliveryAddress')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.ShopOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=840, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_main_photo', to='catalogue.Photo'),
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(related_name='products', to='catalogue.Photo'),
        ),
    ]
