# Generated by Django 3.0.2 on 2020-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('catalogue', '0002_auto_20200120_1458'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopOrder',
            new_name='Order',
        ),
    ]
