# Generated by Django 3.0.2 on 2020-01-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20200120_1458'),
        ('shop', '0002_auto_20200120_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='main_photo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_logo', to='catalogue.Photo'),
            preserve_default=False,
        ),
    ]
