# Generated by Django 3.0.2 on 2020-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200120_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cash'), (1, 'Card')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='products_price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
