# Generated by Django 3.0.2 on 2020-01-21 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200121_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Order'),
        ),
    ]
