# Generated by Django 3.0.2 on 2020-01-24 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('common', '0001_initial'), ('common', '0002_auto_20200121_1904'), ('common', '0003_auto_20200121_1939'), ('common', '0004_customer_phone'), ('common', '0005_auto_20200122_0707')]

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(default=840, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('appartaments', models.CharField(default='', max_length=70)),
                ('house', models.CharField(default='', max_length=128)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='common.Customer')),
            ],
        ),
    ]
