# Generated by Django 3.0.2 on 2020-01-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200121_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='common.DeliveryAddress'),
        ),
    ]
