# Generated by Django 3.0.2 on 2020-01-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='common.Customer'),
        ),
    ]
