# Generated by Django 3.0.2 on 2020-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catalogue', '0001_initial'), ('catalogue', '0002_auto_20200120_1458')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ISO numeric')),
                ('code', models.CharField(max_length=4, verbose_name='Code (ISO)')),
                ('name', models.CharField(max_length=128, verbose_name='Official name (CAPS)')),
                ('symbol', models.CharField(blank=True, max_length=3, null=True, verbose_name='Symbol')),
                ('is_active', models.BooleanField(default=True)),
                ('rate', models.FloatField(default=1.0)),
                ('precision', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
