# Generated by Django 3.0.2 on 2020-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChunkedPhotoData',
        ),
        migrations.DeleteModel(
            name='DeliveryArea',
        ),
        migrations.AlterUniqueTogether(
            name='themeelement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='themeelement',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='themeelement',
            name='theme',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.DeleteModel(
            name='LayoutTheme',
        ),
        migrations.DeleteModel(
            name='ThemeElement',
        ),
    ]
